### PR TITLE
command definition methods

### PR DESCRIPTION
**Pull request by ebrahimkhodadadi**

### CODE REVIEW

**Comment by ZeeLyn** [comment]
Why use the CommandDefinition type as a parameter? I hope to maintain the same style as other method parameters, and [the Dapper library will create the CommandDefinition type parameter](https://github.com/DapperLib/Dapper/blob/47ef1e7100b7ecdb68bcf97432b9674373a6f75c/Dapper/SqlMapper.Async.cs). If you use CommandDefinition as a parameter in Dapper.Extensions, [split it in the CommandExecuteAsync method](https://github.com/ZeeLyn/Dapper.Extensions/blame/36605b7f1394537e4a6dc060dc63c901a45a2578/src/Dapper.Extensions/BaseDapper.Async.cs#L18-L20), and Dapper will Create CommandDefinition type, I think this implementation is not elegant.

**Comment by ebrahimkhodadadi** [comment]
because of the more properties especially CancellationToken if you don't accept this pull request I appreciate that and I will close it

**Comment by ZeeLyn** [comment]
Let me explain again, it is true that using CommandDefinition has more properties, but it cannot be passed directly to Dapper, and creating objects multiple times will consume more performance. thank you so much for your suggestion.

**Comment by ZeeLyn** [comment]
I'm very sorry that I ignored your most critical code. I re-checked the source code of the Dapper library. I think your PR is very good. I hope you can resubmit the PR. I will be very willing to merge your PR. Sorry again!

**Pull request merged**
